### ISSUE TITLE
Broken links on pypi due to out-dated project metadata

### ISSUE THREAD

**Issue by psobolewskiPhD** [BIOP/napari-figure#3]
The various links on pypi and napari-hub are broken due to outdated project metadata:
https://github.com/BIOP/napari-figure/blob/156803902de28d3482356369d7465ee57f96d069/setup.cfg#L4-L29
which refers to https://github.com/romainGuiet/napari-figure repo which doesn't exist.

**Comment by romainGuiet** [comment]
should be fixed with this commit [0cc9136](https://github.com/BIOP/napari-figure/commit/0cc913670ef8ba8c46febac131f12bcdf06440bc) 
thank you for pointing out
